title: Ramblings of a Linux Geek
email: me@skeenan.net
description: > # this means to ignore newlines until "baseurl:"
  Shaun Keenan's rants about technology
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.skeenan.net" # the base hostname & protocol for your site
twitter_username: skeenan2501
github_username:  skeenan947

# Build settings
markdown: kramdown

paginate: 4

author: Shaun Keenan

gems: [jekyll-paginate]
