title = "Shaun Keenan"
baseURL = "/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false
enableRobotsTXT = true

[params]
address = "San Francisco, CA"
email = "me@skeenan.net"
favicon = "/favicon.ico"
firstName = "Shaun"
lastName = "Keenan"
phone = "1-925-408-9425"
profileImage = "img/profile2019-144.webp"
showEducation = true
showExperience = true
showCertifications = false
showOpenSource = false
showProjects = false
showPublications = false
showQr = true
showSkills = true

# GA4
googleAnalyticsID = "G-297211261"

[[params.handles]]
link = "https://www.linkedin.com/in/skeenan/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/skeenan947/"
name = "GitHub"

[[params.handles]]
link = "https://gitlab.com/skeenan/"
name = "GitLab"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
