name: Publish Docker image
on:
    push:

jobs:
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            -
                name: Check out the repo
                uses: actions/checkout@v2
            -
                name: What
                run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and push Branch
                if: GitHub.ref != 'refs/heads/master'
                uses: docker/build-push-action@v2
                with:
                    context: ./
                    file: Dockerfile
                    platforms: linux/amd64,linux/arm64
                    push: true
                    tags: skeenan/skeenan.net:${{ env.BRANCH }}
                    build-args: |
                        BRANCH=${{ env.BRANCH }}
            -
                name: Build and push Release
                if: GitHub.ref == 'refs/heads/master'
                uses: docker/build-push-action@v2
                with:
                    context: ./
                    file: Dockerfile
                    platforms: linux/amd64,linux/arm64
                    push: true
                    tags: skeenan/skeenan.net:latest